// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_cx5_CCtNAyUe-AQcBbPoNH2Nv1XmErw',
    appId: '1:963357026859:web:dfee219c9909a3578a586e',
    messagingSenderId: '963357026859',
    projectId: 'apptranhbeca',
    authDomain: 'apptranhbeca.firebaseapp.com',
    databaseURL: 'https://apptranhbeca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    measurementId: 'G-GV9FHGH3WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdoQtXkn7CwD4RSryIWtGlcM-epOBdrA',
    appId: '1:963357026859:android:3080f1575c42484e8a586e',
    messagingSenderId: '963357026859',
    projectId: 'apptranhbeca',
    databaseURL: 'https://apptranhbeca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfRduYzPZqeWKh2-wheJQmBZ1dYvO--Pc',
    appId: '1:963357026859:ios:a21b1ce97801dcb28a586e',
    messagingSenderId: '963357026859',
    projectId: 'apptranhbeca',
    databaseURL: 'https://apptranhbeca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    iosClientId: '963357026859-a6ugsvq6on5gdhdu46gj3u4tbvigikbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfRduYzPZqeWKh2-wheJQmBZ1dYvO--Pc',
    appId: '1:963357026859:ios:a21b1ce97801dcb28a586e',
    messagingSenderId: '963357026859',
    projectId: 'apptranhbeca',
    databaseURL: 'https://apptranhbeca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    iosClientId: '963357026859-a6ugsvq6on5gdhdu46gj3u4tbvigikbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_cx5_CCtNAyUe-AQcBbPoNH2Nv1XmErw',
    appId: '1:963357026859:web:e0b7a0c4fe8b9da28a586e',
    messagingSenderId: '963357026859',
    projectId: 'apptranhbeca',
    authDomain: 'apptranhbeca.firebaseapp.com',
    databaseURL: 'https://apptranhbeca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    measurementId: 'G-CFLZEQ2LBY',
  );
}
