// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRyctu8q-yjkUbHilAswn6yiv9E9ImCo',
    appId: '1:125965731484:web:0791d92a396a44ff5d4f59',
    messagingSenderId: '125965731484',
    projectId: 'tranh-3d',
    authDomain: 'tranh-3d.firebaseapp.com',
    databaseURL: 'https://tranh-3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    measurementId: 'G-SMQD95WT33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdoQtXkn7CwD4RSryIWtGlcM-epOBdrA',
    appId: '1:963357026859:android:3080f1575c42484e8a586e',
    messagingSenderId: '963357026859',
    projectId: 'apptranhbeca',
    databaseURL: 'https://apptranhbeca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6zUDJzH-VSdJnirfqetU3ZezBqkEkxU',
    appId: '1:125965731484:ios:a62285bd973a923a5d4f59',
    messagingSenderId: '125965731484',
    projectId: 'tranh-3d',
    databaseURL: 'https://tranh-3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6zUDJzH-VSdJnirfqetU3ZezBqkEkxU',
    appId: '1:125965731484:ios:a62285bd973a923a5d4f59',
    messagingSenderId: '125965731484',
    projectId: 'tranh-3d',
    databaseURL: 'https://tranh-3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRyctu8q-yjkUbHilAswn6yiv9E9ImCo',
    appId: '1:125965731484:web:158d0ef418e6c4b55d4f59',
    messagingSenderId: '125965731484',
    projectId: 'tranh-3d',
    authDomain: 'tranh-3d.firebaseapp.com',
    databaseURL: 'https://tranh-3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apptranhbeca.firebasestorage.app',
    measurementId: 'G-X3ZTV0E7Q0',
  );
}
